Improve get_block() errors
Instead of

  thread '<unnamed>' panicked at 'index out of bounds: the len is 0 but the index is 0'

you now get

  hermes::service: Sync failed: Requested block 81a965de1412623ccd1cb3664f4d61a6cb4b9d53b44d779ed918e87bf3493f02 does not exist